### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by lukespragg** [RustOxide/Oxide-2-Patcher#40]
When clicking the "Create Project" button, this error is presented. You can continue still.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at OxidePatcher.NewProjectForm.NewProjectForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HellUnit** [comment]
Ah. This is caused by the fact that "settings" is no longer loaded from formsettings.json. "settings.LastTargetDirectory" in particular. Easy enough to resolve. Just need to initialize as settings.LastTargetDirecory.
